name: "Build"
on:
  release:
    types: [created]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tarball
        run: |
          tar -C connector-definition -czvf connector-definition.tgz model.json configuration.json .hasura-connector

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: connector-definition.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
